<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mst</string>
	</array>
	<key>name</key>
	<string>Milestone</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.ssraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z0-9]+)</string>
			<key>name</key>
			<string>text.ssraw</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ssraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>('.*?')</string>
			<key>name</key>
			<string>started.ssraw</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ssraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(".*?")</string>
			<key>name</key>
			<string>progress.ssraw</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ssraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(`.*?`)</string>
			<key>name</key>
			<string>progress.ssraw</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ssraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\@\.?[^\s]+)</string>
			<key>name</key>
			<string>progress.ssraw</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.quote.ssraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\#.?[^\s]+)</string>
			<key>name</key>
			<string>progress.ssraw</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mst</string>
	<key>uuid</key>
	<string>b5148a52-2a4f-4526-a189-cc27861133d5</string>
</dict>
</plist>
